import {
  createEntity,
  createRelationship,
  type Entity,
  type Relationship
} from "@dark-sloth/types";


export interface PublicationManifest {

  id: string;

  title: string;

  collection: string;

  engine: string;

  records: string[];

  outputs: string[];

}



export function publicationManifestToGraph(
  manifest: PublicationManifest
) {


  const publication =
    createEntity(
      "BOOK",
      manifest.title,
      [],
      "Archive publication generated by Publishing Studio"
    );


  const engine =
    createEntity(
      "PROJECT",
      manifest.engine,
      [],
      "Publishing engine responsible for publication generation"
    );


  const records =
    manifest.records.map(
      id =>
        createEntity(
          "RECOVERY",
          `REC-${id}`,
          [],
          "Archive Recovery Record"
        )
    );



  const relationships: Relationship[] = [];



  relationships.push(

    createRelationship(
      publication.id,
      engine.id,
      "CREATED"
    )

  );



  for (const record of records) {

    relationships.push(

      createRelationship(
        publication.id,
        record.id,
        "REFERENCES"
      )

    );

  }



  return {

    entities: [
      publication,
      engine,
      ...records
    ],


    relationships

  };

}
